//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by READ AVI.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_READAVTYPE                  129
#define IDD_USER_WATERMARK              130
#define IDD_66BIT_USER_WATERMARK        131
#define IDC_USER_WATERMARKINFO          1002
#define IDPSEUDO                        1003
#define IDINITIALIZATION                1006
#define ID_BUTTON_PLAY                  32771
#define ID_BUTTON32774                  32774
#define ID_TIME_SPATIAL                 32775
#define ID_LINEAR_CORRELATION           32777
#define ID_WATERMARK_DETECTION          32777
#define ID_MULTIPURPOSE                 32778
#define ID_RANDOM                       32778
#define ID_DCT_DOMAIN                   32779
#define ID_DWT_DOMAIN                   32780
#define ID_OPEN_ATTACKED                32781
#define ID_BUTTON_STOP                  32782
#define ID_BUTTON_BACK                  32783
#define ID_BUTTON_FORWARD               32784
#define ID_PSEUDO_RANDOM                32785
#define ID_BINARY_IMAGE                 32786
#define ID_BINARY_WATERMARK             32786
#define ID_GRAY_IMAGE                   32787
#define ID_GRAY_WATERMARK               32787
#define ID_COLOR_IMAGE                  32788
#define ID_BUTTON_RESET                 32789
#define ID_WATERMARK_ATTACKED           32791
#define ID_DFT_DOMAIN                   32792
#define ID_BUTTON_BEGIN                 32795
#define ID_BUTTON_END                   32796
#define ID_SAVE_WATERMARK               32797
#define ID_EMBEDDING_REPORT             32798
#define ID_TIME_EMBEDDING2              32799
#define ID_WATERMARK_EXTRACT            32800
#define ID_SAVE_CURRENTFRAME            32801
#define ID_SAVE_CURRENTWATERMARK        32802
#define ID_ATTACKED_REPORT              32803
#define ID_EXTRACT_WATERMARKATTACKED    32804
#define ID_EXTRACT_CURRENT_WMARKATTACKED 32805
#define ID_SAVE_WMARKATTACKED           32806
#define ID_TIME_EMBEDDING_IMPROVED      32807
#define ID_USER_WATERMARK               32808
#define ID_DETECTION_CURRFRAME_SEQUENCE 32810
#define ID_EXTRACT_GOP_WMARKSEQUENCEATTACKED 32812
#define ID_NONBLIND_DETECTION_CURRFRAME_SEQUENCE 32814
#define ID_NOBLINDEXTRACT_CURRENT_WMARKATTACKED 32815
#define ID_NOBLINDEXTRACT_GOP_WMARKSEQUENCEATTACKED 32816
#define ID_EXTRACT_CURRENT_WMARKSEQUENCEATTACKED 32817
#define ID_EDGE_ENHANCE                 32818
#define ID_IMAGE_BLUR                   32819
#define ID_EDGE_DETECTION               32820
#define ID_FRAME_DIFFERENCE             32821
#define ID_SAVE_CURRENT_ORIGINAL_FRAME  32822
#define ID_BUTTON32823                  32823
#define ID_PREDICTION_FILTER            32824
#define ID_SAVE_DIFFERENCEIMAGE         32825
#define ID_TIME_AXIS_EMBEDDING          32826
#define ID_66bit_User_Watermark         32827
#define ID_EXTRACT_WATERMARK_ALONG_TIME_AXIS 32828
#define ID_EXTRACT_WMARKSEQUENCEALONGTIMEAXISATTACKED 32830
#define ID_ADAPTIVE_TIME_EMBEDDING_SPREADSPECTRUM 32831
#define ID_SAVE_CURRENT_ATTACKED_FRAME  32832
#define ID_PREDICTION_FILTER_3x3        32835
#define ID_Laplacian_Filter             32836
#define ID_EXTRACTION_CURRFRAME_SSSEQUENCE 32837
#define ID_EXTRACTION_CURRFRAME_SSSEQUENCE_ATTACKED 32838
#define ID_TIME_AXIS_BITPLANE_EMBEDDING 32839
#define ID_EXTRACT_BITPLANEWATERMARK_ALONG_TIME_AXIS 32840
#define ID_EXTRACT_BITPLANEWMARKSEQUENCEALONGTIMEAXISATTACKED 32841
#define ID_WATERMARK_ATTACKED_COLOR     32842
#define ID_TIME_AXIS_EMBEDDING_DUAL_WATERMARKS 32844
#define ID_EXTRACTION_CURRFRAME_ADDEDSSSEQUENCE 32845
#define ID_EXTRACTION_CURRFRAME_ADDEDSSSEQUENCE_ATTACKED 32846
#define ID_BLINDEXTRACTION_CURRFRAME_ADDEDSSSEQUENCE_ATTACKED 32848
#define ID_ADAPTIVE_DCT_EMBEDDING       32849
#define ID_SAVE_PSEUDORANDOM_WATERMARK  32850
#define ID_EXTRACTION_CURRFRAME_DCTDOMAINADAPTIVE 32851
#define ID_EXTRACTION_CURRFRAME_DCTDOMAIN_ADAPTIVE_ATTACKED 32852
#define ID_DEW_ALGORITHM                32853
#define ID_Calculation_JND              32854

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32855
#define _APS_NEXT_CONTROL_VALUE         1007
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
